# Generated by Django 2.1.5 on 2019-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vin_charts', '0002_auto_20190130_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmissions',
            field=models.ManyToManyField(to='vin_charts.Transmission'),
        ),
    ]
