# Generated by Django 2.1.5 on 2019-01-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vin_charts', '0003_auto_20190130_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chassis',
            name='notes',
            field=models.ManyToManyField(to='vin_charts.Note'),
        ),
        migrations.AddField(
            model_name='engine',
            name='notes',
            field=models.ManyToManyField(to='vin_charts.Note'),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='notes',
            field=models.ManyToManyField(to='vin_charts.Note'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='notes',
            field=models.ManyToManyField(to='vin_charts.Note'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.ManyToManyField(to='vin_charts.Note'),
        ),
    ]
