# Generated by Django 2.1.5 on 2019-02-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vin_charts', '0004_auto_20190131_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('chassis', models.ManyToManyField(to='vin_charts.Chassis')),
                ('engines', models.ManyToManyField(to='vin_charts.Engine')),
                ('transmissions', models.ManyToManyField(to='vin_charts.Transmission')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.Type'),
        ),
    ]
